# Generated by Django 4.2 on 2023-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_categoria_nome_alter_categoria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
