# Generated by Django 4.2 on 2023-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'Carrinho'),
                    (2, 'Realizado'),
                    (3, 'Pago'),
                    (4, 'Entregue'),
                ],
                default=1,
            ),
        ),
    ]
