# Generated by Django 4.2.3 on 2023-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_categoria_descricao_alter_editora_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
